[package]
name = "icarus_models"
version = "0.8.1"
edition = "2024"
rust-version = "1.90"
description = "models used for the icarus project"
license = "MIT"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145" }
rand = { version = "0.9.2" }
time = { version = "0.3.44", features = ["formatting", "macros", "parsing", "serde"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
josekit = { version = "0.10.3" }
utoipa = { version = "5.4.0", features = ["uuid", "time"] }

[dev-dependencies]
tempfile = { version = "3.23.0" }
