[package]
name = "icarus-models"
version = "0.1.10"
edition = "2024"
description = "models used for the icarus project"
license = "MIT"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
